#If you want to change what the plugin does on launch
checkpointonly: true
joinloggingonlaunch: true

#Block Types
checkpointblock: "gold block"
jumpblock: "diamond block"
finishblock: "emerald block"
speedblock: "iron block"
#Locations
finishlocation:
  - 0.0 #x
  - 0.0 #y
  - 0.0 #z

#Sounds
checkpointsound: "BLOCK_PISTON_EXTEND"
boostsound: "ENTITY_BAT_TAKEOFF"
speedsound: "ENTITY_ENDER_DRAGON_FLAP"
#Messages
checkpointmessage: "&eCheckpoint &creached!"
boostmessage: "&5WHOOSH!"
speedtext: "&5WHOOSH!"
finishmessage: "&eFinish line &ereached!"

#values
jumpvalue: 10
speedvalue: 10
#items Not implemented yet.
gobackitem:
  name : "&cGo Back"
  mat : "redstone"
  lore: #can only have 2 lines
    - "&eThis item will allow you to go back to your last checkpoint"
    - "&eOr use /back"
  index: 8 #the slot where the item will appear in!