#-----------------------------------------------------------
#Put your license key here!
licensekey: "no key"
#-----------------------------------------------------------
#generic settings
parkoursettings:
  gamesettings: #gamesettings
    spawnlocation:
      world: "world"
      x: 0.0
      y: 0.0
      z: 0.0
  blocks:
    checkpointblock: "GOLD_BLOCK"
    nextlevelblock: "EMERALD_BLOCK"
  sounds:
    menuclicksound: "BLOCK_SCAFFOLDING_BREAK"
    nextlevelsound: "BLOCK_AMETHYST_BLOCK_PLACE"
    checkpointsound: "BLOCK_NOTE_BLOCK_PLING"
  messages:
    checkpointmessage: "&aCheckpoint &cReached!"
    finishmessage: "&aFinish Line &eReached!"
  items:
    goback:
      name: "&c[&aGo Back&a]"
      material: "REDSTONE"
    levelselector:
      name: "&c[&aLevel Selector]"
      material: "CLOCK"
  database:
    usesql: false # false = use sqlite, true = use mysql
    link: "localhost:3306"
    username: "root"
    password: ""
    table: "KEP" #All tables start with 'kr_'

levels:
  - name: "Default"
    icon: "GREEN_WOOL"
    x: 0.0
    y: 0.0
    z: 0.0
    difficulty: "easy"
    creator: "Default"
    points: 1
    reward: 15
  - name: "Default"
    icon: "RED_WOOL"
    x: 0.0
    y: 0.0
    z: 0.0
    difficulty: "easy"
    creator: "Default"
    points: 1
    reward: 15




