
# generic settings
parkoursettings:
  leaderboardrefreshrate: 30 # minutes
  gamesettings:
    checkpointonly: false
    jumpvalue: 10
    boostvalue: 10
    spawnlocation:
      world: world
      x: -111.5
      y: 57.0
      z: 103.5
  blocks:
    checkpointblock: GOLD_BLOCK
    nextlevelblock: EMERALD_BLOCK
    boostblock: DIAMOND_BLOCK
    floatblock: END_STONE
  sounds:
    menuclicksound: BLOCK_SCAFFOLDING_BREAK
    nextlevelsound: BLOCK_AMETHYST_BLOCK_PLACE
    checkpointsound: BLOCK_NOTE_BLOCK_PLING
  colors: # future options
    primary: GREEN
    secondary: RED
    gray: LIGHT_GRAY
    error: DARK_RED
    info: AQUA
  messages:
    checkpointmessage: '&aCheckpoint &cReached!'
    finishmessage: '&aFinish Line &eReached!'
    youcantdothis: '&cYou cannot do this.'
  items:
    goback:
      name: '&c[&aGo Back&c]'
      material: REDSTONE
    levelselector:
      name: '&c[&aLevel Selector&c]'
      material: CLOCK
  database:
    usesql: false # false = use sqlite, true = use mysql
    link: localhost:3306
    username: root
    password: ''
    table: KEP # All tables start with 'kr_'


levels:
  - name: Example
    creator: Krekkers
    x: 0.0
    y: 57.0
    z: 0.0
    difficulty: 1
    icon: POPPY
    points: 0
    reward: 15

leaderboards:
  - title: Test
    type: Type
    limit: 1
    x: 0.0
    y: 0.0
    z: 0.0
    yoffset: -0.3














