#-----------------------------------------------------------
#Put your license key here!
licensekey: "no key"
#-----------------------------------------------------------
#generic settings
parkoursettings:
  leaderboardrefreshrate: 30 #minutes
  gamesettings: #gamesettings
    spawnlocation:
      world: "world"
      x: 0.0
      y: 0.0
      z: 0.0
  blocks:
    checkpointblock: GOLD_BLOCK
    nextlevelblock: EMERALD_BLOCK
    boostblock: DIAMOND_BLOCK
  sounds:
    menuclicksound: "BLOCK_SCAFFOLDING_BREAK"
    nextlevelsound: "BLOCK_AMETHYST_BLOCK_PLACE"
    checkpointsound: "BLOCK_NOTE_BLOCK_PLING"
  colors: #future options
    primary: GREEN
    secondary: RED
    gray: LIGHT_GRAY
    error: RED
    info: CYAN
  messages:
    checkpointmessage: "&aCheckpoint &cReached!"
    finishmessage: "&aFinish Line &eReached!"
    youcantdothis: "&cYou cannot do this."
  items:
    goback:
      name: "&c[&aGo Back&a]"
      material: "REDSTONE"
    levelselector:
      name: "&c[&aLevel Selector]"
      material: "CLOCK"
  database:
    #!Don't touch if you don't know what you are doing!
    usesql: false # false = use sqlite, true = use mysql
    levelsinsql: false #will save levels and load levels outside the config file and store it in the sql(ite) database
    link: "" #leave empty if you have usesql on false
    username: "" #leave empty if you have usesql on false
    password: "" #leave empty if you have usesql on false
    table: "KEP" #All tables start with 'kr_'
  multipliers: #default multiplier is 1.0
    - rank: "krekks.multiplier.mvp"
      multiplier: 1.0
    - rank: "krekks.multiplier.vip"
      multiplier: 1.5
  rankSettings:
    - rank: "krekks.vip"
      freepoints: 10
      multiplier: 1.5


menuoptions:
  buttonicons:
    previous:
    currentpage:
    next:
    close:


  

levels:
  - name: "Default"
    icon: "GREEN_WOOL"
    rotation: 0
    x: 0.0
    y: 0.0
    z: 0.0
    difficulty: "easy"
    creator: "Default"
    points: 0
    reward: 15

leaderboards:
  - name: "Placeholder"
    id: 1
    limit: 5
    type: FC
    yoffset: 5 #location offset
    position:
      x: 0.0
      y: 0.0 # y indicates the 1st line of the leaderboard
      z: 0.0


