#If you want to change what the plugin does on launch
checkpointonly: false
joinloggingonlaunch: true
autostart: false

menuclicksound: "BLOCK_SCAFFOLDING_BREAK"

#Block Types
checkpointblock: "gold block"
jumpblock: "diamond block"
finishblock: "emerald block"
boostblock: "iron block"
elytrablock: "PURPUR_PILLAR"


#Sounds
nextlevelsound: "BLOCK_AMETHYST_BLOCK_PLACE"
checkpointsound: "BLOCK_NOTE_BLOCK_PLING"
jumpsound: "BLOCK_PISTON_EXTEND"
boostsound: "ENTITY_FIREWORK_ROCKET_LAUNCH"
elytrasound: "ENTITY_ENDER_DRAGON_FLAP"
#Messages
checkpointmessage: "&eCheckpoint &cReached!"
jumpmessage: "&cWHOOSH!"
boostmessage: "&eWHOOSH!"
elytramessage: "&cWHOOSH!"
finishmessage: "&eFinish Line &eReached!"

#values
jumpvalue: 10
boostvalue: 10
elytravalue: 15
#Item
backitemname: "&eGo &cBack"
backmaterial: "REDSTONE"


levels:
  - 1 :
    name: "Default"
    icon: "GREEN_WOOL"
    x: 0.0
    y: 0.0
    z: 0.0
    difficulty: "easy"
    creator: ""
    points: 1
  - 2 :
    name: "Default 2"
    icon: "GREEN_WOOL"
    x: 1.0
    y: 0.5
    z: 0.15
    difficulty: "easy"
    creator: ""
    points: 1



