#generic settings
parkoursettings:
  gamesettings:
    checkpointonly: false
    jumpvalue: 10
    boostvalue: 10
    spawnlocation:
      world: "world"
      x: 0.0
      y: 0.0
      z: 0.0
  blocks:
    checkpointblock: "GOLD_BLOCK"
    jumpblock: "DIAMOND_BLOCK"
    nextlevelblock: "EMERALD_BLOCK"
    boostblock: "IRON_BLOCK"
  sounds:
    menuclicksound: "BLOCK_SCAFFOLDING_BREAK"
    nextlevelsound: "BLOCK_AMETHYST_BLOCK_PLACE"
    checkpointsound: "BLOCK_NOTE_BLOCK_PLING"
    jumpsound: "BLOCK_PISTON_EXTEND"
    boostsound: "ENTITY_FIREWORK_ROCKET_LAUNCH"
  messages:
    checkpointmessage: "&eCheckpoint &cReached!"
    jumpmessage: "&cWHOOSH!"
    boostmessage: "&eWHOOSH!"
    elytramessage: "&cWHOOSH!"
    finishmessage: "&eFinish Line &eReached!"
  items:
    goback:
      backitemname: "&eGo &cBack"
      backmaterial: "REDSTONE"


levels:
  - 1 :
    name: "Default"
    icon: "GREEN_WOOL"
    x: 0.0
    y: 0.0
    z: 0.0
    difficulty: "easy"
    creator: ""
    points: 1
  - 2 :
    name: "Default 2"
    icon: "GREEN_WOOL"
    x: 1.0
    y: 0.5
    z: 0.15
    difficulty: "easy"
    creator: ""
    points: 1



