#If you want to change what the plugin does on launch
checkpointonly: true
joinloggingonlaunch: true
autostart: false
usepermissions: false

#Block Types
checkpointblock: "gold block"
jumpblock: "diamond block"
finishblock: "emerald block"
boostblock: "iron block"
#Locations
finishlocation:
  - 0.0 #x
  - 0.0 #y
  - 0.0 #z

#Sounds
checkpointsound: "PISTON_EXTEND"
jumpsound: "BAT_TAKEOFF"
boostsound: "ENDERDRAGON_WINGS"
#Messages
checkpointmessage: "&eCheckpoint &creached!"
jumpmessage: "&5WHOOSH!"
boostmessage: "&3WHOOSH!"
finishmessage: "&eFinish line &ereached!"

#values
jumpvalue: 10
boostvalue: 10
#Item
backitemname: "&eGo &cBack"
backmaterial: "REDSTONE"




