#If you want to change what the plugin does on launch
checkpointonly: false
joinloggingonlaunch: true
autostart: false

#Block Types
checkpointblock: "gold block"
jumpblock: "diamond block"
finishblock: "emerald block"
boostblock: "iron block"
elytrablock: "PURPUR_PILLAR"
#Locations
finishlocation:
  - 0.0     #x
  - 100.0   #y
  - 0.0     #z
spawnlocation:
  - 0.0     #x
  - 50.0    #y
  - 0.0     #z


#Sounds
checkpointsound: "BLOCK_NOTE_BLOCK_PLING"
jumpsound: "BLOCK_PISTON_EXTEND"
boostsound: "ENTITY_FIREWORK_ROCKET_LAUNCH"
elytrasound: "ENTITY_ENDER_DRAGON_FLAP"
#Messages
checkpointmessage: "&eCheckpoint &cReached!"
jumpmessage: "&cWHOOSH!"
boostmessage: "&eWHOOSH!"
elytramessage: "&cWHOOSH!"
finishmessage: "&eFinish Line &eReached!"

#values
jumpvalue: 10
boostvalue: 10
elytravalue: 15
#Item
backitemname: "&eGo &cBack"
backmaterial: "REDSTONE"




